"""Owner: drafting.application.migration

Used by: architecture smoke, roadmap migration slices, and backend architecture tests.
Does not own: DraftRun runtime behavior, prompt text, provider calls, or compatibility imports.
Architecture doc: docs/adr/2026-07-05-draftrun-legacy-surface-oop-migration.md
"""
from __future__ import annotations
from dataclasses import dataclass


class LegacyMigrationCluster:
    COMPATIBILITY_SHELL = "compatibilityShell"
    CONTEXT_ARTIFACTS = "contextArtifacts"
    SOURCE_EVIDENCE = "sourceEvidence"
    PLANNING = "planning"
    CANDIDATE_GENERATION = "candidateGeneration"
    VALIDATION = "validation"
    RANKING_REVISION = "rankingRevision"
    FINAL_QUALITY = "finalQuality"
    HITL = "hitl"
    SHARED_OPERATION_SUPPORT = "sharedOperationSupport"
    ALL = (
        COMPATIBILITY_SHELL,
        CONTEXT_ARTIFACTS,
        SOURCE_EVIDENCE,
        PLANNING,
        CANDIDATE_GENERATION,
        VALIDATION,
        RANKING_REVISION,
        FINAL_QUALITY,
        HITL,
        SHARED_OPERATION_SUPPORT,
    )


class LegacyModuleDisposition:
    SERVICE = "service"
    POLICY = "policy"
    COMPONENT = "component"
    DTO = "dto"
    PRIVATE_HELPER = "privateHelper"
    COMPATIBILITY_SHIM = "compatibilityShim"
    DELETE_AFTER_MIGRATION = "deleteAfterMigration"
    ALL = (SERVICE, POLICY, COMPONENT, DTO, PRIVATE_HELPER, COMPATIBILITY_SHIM, DELETE_AFTER_MIGRATION)


class LegacyHelperDisposition:
    SERVICE = "service"
    POLICY = "policy"
    COMPONENT = "component"
    DTO = "dto"
    PRIVATE_HELPER = "privateHelper"
    COMPATIBILITY_SHIM = "compatibilityShim"
    DELETE_AFTER_MIGRATION = "deleteAfterMigration"
    ALL = (SERVICE, POLICY, COMPONENT, DTO, PRIVATE_HELPER, COMPATIBILITY_SHIM, DELETE_AFTER_MIGRATION)


@dataclass(frozen=True)
class LegacyPublicHelperDisposition:
    helper_name: str
    helper_disposition: str
    target_owner: str
    target_visibility: str
    rationale: str

    def to_payload(self) -> dict[str, str]:
        return {
            "helperName": self.helper_name,
            "helperDisposition": self.helper_disposition,
            "targetOwner": self.target_owner,
            "targetVisibility": self.target_visibility,
            "rationale": self.rationale,
        }


@dataclass(frozen=True)
class LegacyDraftRunModuleDisposition:
    current_module: str
    cluster: str
    target_package: str
    module_disposition: str
    target_owner: str
    migration_slice: str
    compatibility_strategy: str
    public_helpers: tuple[LegacyPublicHelperDisposition, ...]
    notes: str

    def to_payload(self) -> dict[str, object]:
        return {
            "currentModule": self.current_module,
            "cluster": self.cluster,
            "targetPackage": self.target_package,
            "moduleDisposition": self.module_disposition,
            "targetOwner": self.target_owner,
            "migrationSlice": self.migration_slice,
            "compatibilityStrategy": self.compatibility_strategy,
            "publicHelpers": [helper.to_payload() for helper in self.public_helpers],
            "notes": self.notes,
        }


def _public_helpers(names: tuple[str, ...], helper_disposition: str, target_owner: str, rationale: str) -> tuple[LegacyPublicHelperDisposition, ...]:
    target_visibility = "private" if helper_disposition == LegacyHelperDisposition.PRIVATE_HELPER else "package"
    return tuple(
        LegacyPublicHelperDisposition(
            helper_name=name,
            helper_disposition=helper_disposition,
            target_owner=target_owner,
            target_visibility=target_visibility,
            rationale=rationale,
        )
        for name in names
    )


def _entry(current_module: str, cluster: str, target_package: str, module_disposition: str, target_owner: str, migration_slice: str, compatibility_strategy: str, public_helper_names: tuple[str, ...], public_helper_disposition: str, helper_rationale: str, notes: str) -> LegacyDraftRunModuleDisposition:
    return LegacyDraftRunModuleDisposition(
        current_module=current_module,
        cluster=cluster,
        target_package=target_package,
        module_disposition=module_disposition,
        target_owner=target_owner,
        migration_slice=migration_slice,
        compatibility_strategy=compatibility_strategy,
        public_helpers=_public_helpers(public_helper_names, public_helper_disposition, target_owner, helper_rationale),
        notes=notes,
    )


LEGACY_DRAFT_RUN_SURFACE_INVENTORY: tuple[LegacyDraftRunModuleDisposition, ...] = (
    _entry("backend/app/application/deterministic_draft_candidate_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DeterministicFallbackDraftCandidateService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; fallback behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_draft_planning_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DeterministicDraftPlanningFallbackService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_draft_planning_step_services.py", "planning", "backend/app/drafting/application/planning", "policy", "backend.app.drafting.application.planning.DeterministicDraftPlanningFallbackStepServices", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "planning cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_draft_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DeterministicFallbackDraftService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; fallback behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_evidence_interpretation.py", "sourceEvidence", "backend/app/drafting/application/evidence", "policy", "backend.app.drafting.application.evidence.DeterministicEvidenceInterpretationFallbackPolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_evidence_interpretation_step_service.py", "sourceEvidence", "backend/app/drafting/application/evidence", "service", "backend.app.drafting.application.evidence.DeterministicEvidenceInterpretationFallbackStepService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_external_evidence_synthesis.py", "sourceEvidence", "backend/app/drafting/application/evidence", "policy", "backend.app.drafting.application.evidence.DeterministicExternalEvidenceSynthesisFallbackPolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_external_evidence_synthesis_step_service.py", "sourceEvidence", "backend/app/drafting/application/evidence", "service", "backend.app.drafting.application.evidence.DeterministicExternalEvidenceSynthesisFallbackStepService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_pairwise_ranking.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DeterministicFallbackPairwiseRankingPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; fallback behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_rhetorical_plan_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DeterministicRhetoricalPlanFallbackService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_rhetorical_plan_step_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DeterministicRhetoricalPlanFallbackStepService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_source_research_plan_service.py", "sourceEvidence", "backend/app/drafting/application/evidence", "service", "backend.app.drafting.application.evidence.DeterministicSourceResearchPlanFallbackService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/deterministic_source_research_step_service.py", "sourceEvidence", "backend/app/drafting/application/evidence", "service", "backend.app.drafting.application.evidence.DeterministicSourceResearchFallbackStepService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; deterministic fallback behavior lives in the target owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_alternative_angle_audit.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftAlternativeAngleAuditComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; fallback behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_alternative_angle_request_trace", "build_alternative_angle_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_alternative_angle_candidate_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftAlternativeAngleCandidateService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_alternative_angle_prompts.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftAlternativeAnglePromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_alternative_angle_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_alternative_angle_route_service.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftAlternativeAngleRouteService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "compatibilityShell cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_alternative_angle_tournament_service.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftAlternativeAngleTournamentService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "compatibilityShell cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_article_dossier_builder.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.ArticleDossierBuilderComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_article_memory_service.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "service", "backend.app.drafting.application.artifacts.DraftArticleMemoryService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("context_pack_from_payload", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "contextArtifacts cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_attribution_markers.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftAttributionMarkersComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("attribution_markers_for_claim", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_attribution_requirements.py", "validation", "backend/app/drafting/application/validation", "policy", "backend.app.drafting.application.validation.DraftAttributionRequirementsPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("normalize_attribution_requirements", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "validation cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_audit.py", "candidateGeneration", "backend/app/drafting/application/generation", "component", "backend.app.drafting.application.generation.DraftCandidateAuditComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_candidate_request_trace", "build_candidate_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "candidateGeneration cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_direction_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftCandidateDirectionService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_generation_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftCandidateGenerationService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_prompts.py", "candidateGeneration", "backend/app/drafting/application/generation", "component", "backend.app.drafting.application.generation.DraftCandidatePromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_draft_candidate_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "candidateGeneration cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_provider_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftCandidateProviderService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_publishability.py", "candidateGeneration", "backend/app/drafting/application/generation", "policy", "backend.app.drafting.application.generation.DraftCandidatePublishabilityPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "candidateGeneration cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_result.py", "candidateGeneration", "backend/app/drafting/application/generation", "dto", "backend.app.drafting.application.generation.DraftCandidateResultDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "candidateGeneration cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_selection_block.py", "candidateGeneration", "backend/app/drafting/application/generation", "dto", "backend.app.drafting.application.generation.DraftCandidateSelectionBlockDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("candidate_selection_blocked_payload", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "candidateGeneration cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_candidate_selection_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftCandidateSelectionService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_context_pack_builder.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.DraftContextPackBuilderComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("context_pack_for_role", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_directed_revision_prompts.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftDirectedRevisionPromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_directed_revision_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_directed_revision_service.py", "rankingRevision", "backend/app/drafting/application/revision", "service", "backend.app.drafting.application.revision.DraftDirectedRevisionService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "rankingRevision cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_critique_audit.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftEditorialCritiqueAuditComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_editorial_critique_request_trace", "build_editorial_critique_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_critique_flow.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftEditorialCritiqueFlowService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("append_editorial_critique", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_critique_parser.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftEditorialCritiqueParserComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("parse_editorial_critique", "critique_dimension", "editorial_risk", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_critique_prompts.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftEditorialCritiquePromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_editorial_critique_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_critique_service.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftEditorialCritiqueService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_revision_evaluator.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DraftEditorialRevisionEvaluatorPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_editorial_revision_goals.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftEditorialRevisionGoalsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_feasibility_gate.py", "sourceEvidence", "backend/app/drafting/application/evidence", "policy", "backend.app.drafting.application.evidence.FeasibilityGatePolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_feasibility_policy.py", "sourceEvidence", "backend/app/drafting/application/evidence", "policy", "backend.app.drafting.application.evidence.FeasibilityPolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("decide_feasibility", "decision", "has_safe_context_without_candidate", "has_alternative_claims_without_source", "has_source_evidence", "has_brief_evidence", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_assessment.py", "finalQuality", "backend/app/drafting/application/final_quality", "policy", "backend.app.drafting.application.final_quality.DraftFinalQualityAssessmentPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("gate_payload", "repair_instruction", "repair_rejection_reasons", "repair_goals", "internal_jargon_leaks", "source_dump_risk", "candidate_report", "worst", "severity", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "finalQuality cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_attribution.py", "finalQuality", "backend/app/drafting/application/final_quality", "privateHelper", "backend.app.drafting.application.final_quality.DraftFinalQualityAttributionHelpers", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("effective_finding_counts", "attribution_finding_split", "is_actionable_finding", "suppressed_reason", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "finalQuality cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_contract.py", "finalQuality", "backend/app/drafting/application/final_quality", "dto", "backend.app.drafting.application.final_quality.DraftFinalQualityContractDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_final_quality_contract", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "finalQuality cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_gate.py", "finalQuality", "backend/app/drafting/application/final_quality", "policy", "backend.app.drafting.application.final_quality.DraftFinalQualityGatePolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "finalQuality cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_gate_evaluator.py", "finalQuality", "backend/app/drafting/application/final_quality", "policy", "backend.app.drafting.application.final_quality.DraftFinalQualityGateEvaluatorPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "finalQuality cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_gate_payloads.py", "finalQuality", "backend/app/drafting/application/final_quality", "dto", "backend.app.drafting.application.final_quality.DraftFinalQualityGatePayloadsDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("final_decision", "not_run_payload", "strings", "last", "worst_status", "gate_improved", "severity", "unique", "dedupe", "dict_value", "list_value", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "finalQuality cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_repair_loop.py", "finalQuality", "backend/app/drafting/application/final_quality", "component", "backend.app.drafting.application.final_quality.DraftFinalQualityRepairLoopComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "finalQuality cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_review_parser.py", "finalQuality", "backend/app/drafting/application/final_quality", "component", "backend.app.drafting.application.final_quality.DraftFinalQualityReviewParserComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("normalize_final_quality_review", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "finalQuality cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_review_prompts.py", "finalQuality", "backend/app/drafting/application/final_quality", "component", "backend.app.drafting.application.final_quality.DraftFinalQualityReviewPromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_final_quality_review_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "finalQuality cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_final_quality_review_service.py", "finalQuality", "backend/app/drafting/application/final_quality", "service", "backend.app.drafting.application.final_quality.DraftFinalQualityReviewService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "finalQuality cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_generation_audit.py", "candidateGeneration", "backend/app/drafting/application/generation", "component", "backend.app.drafting.application.generation.DraftGenerationAuditComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_draft_request_trace", "build_draft_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "candidateGeneration cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_generation_params.py", "candidateGeneration", "backend/app/drafting/application/generation", "dto", "backend.app.drafting.application.generation.DraftGenerationParamsDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("generation_params_for_profile", "generation_params_for_attempt", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "candidateGeneration cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_generation_service.py", "candidateGeneration", "backend/app/drafting/application/generation", "service", "backend.app.drafting.application.generation.DraftGenerationService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "candidateGeneration cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_human_comment_quality_service.py", "hitl", "backend/app/drafting/application/hitl", "service", "backend.app.drafting.application.hitl.DraftHumanCommentQualityService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_human_comment_quality_messages", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "hitl cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_human_comment_revision_service.py", "hitl", "backend/app/drafting/application/hitl", "service", "backend.app.drafting.application.hitl.DraftHumanCommentRevisionService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_human_comment_revision_messages", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "hitl cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_llm_validation_audit.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftLlmValidationAuditComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_llm_validation_request_trace", "build_llm_validation_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_llm_validation_observations.py", "validation", "backend/app/drafting/application/validation", "privateHelper", "backend.app.drafting.application.validation.DraftLlmValidationObservationsHelpers", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("normalize_llm_validator_id", "is_llm_observation_like", "llm_observation", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_llm_validation_parser.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftLlmValidationParserComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("parse_llm_validation_report", "parse_llm_validation_findings", "status_for_llm_payload", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_llm_validation_prompts.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftLlmValidationPromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_llm_validation_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_llm_validation_service.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftLlmValidationService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_material_plan_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DraftMaterialPlanService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_model_role_resolver.py", "sharedOperationSupport", "backend/app/drafting/application/operations", "component", "backend.app.drafting.application.operations.DraftModelRoleResolverComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("select_model_for_role", "unconfigured_model_selection", "select_model_for_final_gate", "selection_for_attempt", "with_model_selection", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sharedOperationSupport cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_pairwise_ranking_payloads.py", "rankingRevision", "backend/app/drafting/application/revision", "dto", "backend.app.drafting.application.revision.DraftPairwiseRankingPayloadsDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("report_from_payload", "validate_pairwise_payload", "attempt_record", "dimension_scores", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "rankingRevision cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_pairwise_ranking_prompts.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftPairwiseRankingPromptsComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_pairwise_ranking_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_pairwise_ranking_service.py", "rankingRevision", "backend/app/drafting/application/revision", "service", "backend.app.drafting.application.revision.DraftPairwiseRankingService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "rankingRevision cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_planning_audit.py", "planning", "backend/app/drafting/application/planning", "component", "backend.app.drafting.application.planning.DraftPlanningAuditComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("build_planning_request_trace", "build_planning_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "planning cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_planning_prompts.py", "planning", "backend/app/drafting/application/planning", "component", "backend.app.drafting.application.planning.DraftPlanningPromptsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("build_material_plan_messages", "build_draft_strategy_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "planning cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_planning_result.py", "planning", "backend/app/drafting/application/planning", "dto", "backend.app.drafting.application.planning.DraftPlanningStepResultDTO", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "planning cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_post_contract_builder.py", "sourceEvidence", "backend/app/drafting/application/evidence", "component", "backend.app.drafting.application.evidence.PostContractBuilderComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sourceEvidence cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_prompt_builder.py", "candidateGeneration", "backend/app/drafting/application/generation", "component", "backend.app.drafting.application.generation.DraftPromptBuilderComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("build_draft_prompt_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "candidateGeneration cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_provider_error_utils.py", "sharedOperationSupport", "backend/app/drafting/application/operations", "privateHelper", "backend.app.drafting.application.operations.DraftProviderErrorUtilsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("safe_provider_error", "raw_response_excerpt", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "sharedOperationSupport cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_public_evidence_step_service.py", "sourceEvidence", "backend/app/drafting/application/evidence", "service", "backend.app.drafting.application.evidence.PublicEvidenceStepService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "sourceEvidence cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_quality_gate.py", "sourceEvidence", "backend/app/drafting/application/evidence", "policy", "backend.app.drafting.application.evidence.DraftQualityGatePolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "sourceEvidence cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_ranking_revision_mapping.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftRankingRevisionMappingComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("candidate_by_id", "candidate_to_draft", "last_revised", "final_reason", "last", "safe_error", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_ranking_revision_result.py", "rankingRevision", "backend/app/drafting/application/revision", "dto", "backend.app.drafting.application.revision.DraftRankingRevisionResultDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "rankingRevision cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_ranking_revision_service.py", "rankingRevision", "backend/app/drafting/application/revision", "service", "backend.app.drafting.application.revision.DraftRankingRevisionService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "rankingRevision cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_acceptance_policy.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DraftRevisionAcceptancePolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("acceptance_decision", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_goal_evaluator.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DraftRevisionGoalEvaluatorPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_instruction_builder.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftRevisionInstructionBuilderComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_loop_config.py", "rankingRevision", "backend/app/drafting/application/revision", "dto", "backend.app.drafting.application.revision.DraftRevisionLoopConfigDTO", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("revision_iteration_limit", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "rankingRevision cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_loop_cycle_runner.py", "rankingRevision", "backend/app/drafting/application/revision", "component", "backend.app.drafting.application.revision.DraftRevisionLoopCycleRunnerComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "rankingRevision cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_loop_policy.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DraftRevisionLoopPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("combined_validation", "pairwise_winner", "failed_cycle", "constraints_from_unresolved", "constraints_from_rejection", "candidate_id", "dict_or_empty", "string_list", "last_value", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_loop_service.py", "rankingRevision", "backend/app/drafting/application/revision", "service", "backend.app.drafting.application.revision.DraftRevisionLoopService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "rankingRevision cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_regression.py", "rankingRevision", "backend/app/drafting/application/revision", "policy", "backend.app.drafting.application.revision.DraftRevisionRegressionPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "policy", "behavioral decision helper becomes a method on the target policy owner", "rankingRevision cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_revision_rejected_moves.py", "rankingRevision", "backend/app/drafting/application/revision", "privateHelper", "backend.app.drafting.application.revision.DraftRevisionRejectedMovesHelpers", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("rejected_moves_from_cycle", "constraints_from_rejected_moves", "constraints_from_editorial_goals", "goal_messages", "cycle_stop_reason", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "rankingRevision cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rhetorical_plan_audit.py", "planning", "backend/app/drafting/application/planning", "component", "backend.app.drafting.application.planning.DraftRhetoricalPlanAuditComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("build_rhetorical_plan_request_trace", "build_rhetorical_plan_result_trace", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "planning cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rhetorical_plan_prompts.py", "planning", "backend/app/drafting/application/planning", "component", "backend.app.drafting.application.planning.DraftRhetoricalPlanPromptsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("build_rhetorical_plan_messages", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "planning cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rhetorical_plan_retry.py", "planning", "backend/app/drafting/application/planning", "component", "backend.app.drafting.application.planning.DraftRhetoricalPlanRetryComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "planning cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rhetorical_plan_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DraftRhetoricalPlanService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_pack_compiler.py", "sourceEvidence", "backend/app/drafting/application/evidence", "component", "backend.app.drafting.application.evidence.RulePackCompilerComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sourceEvidence cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_pack_from_registry.py", "sourceEvidence", "backend/app/drafting/application/evidence", "privateHelper", "backend.app.drafting.application.evidence.RulePackFromRegistryComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("rules_from_registry", "requirements_from_registry", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "sourceEvidence cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_pack_sections.py", "sourceEvidence", "backend/app/drafting/application/evidence", "component", "backend.app.drafting.application.evidence.RulePackSectionsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("publisher_constraints", "candidate_constraints", "evidence_requirements", "dramaturgy_requirements", "topic_fit_requirements", "forbidden_moves", "quality_rubric", "rule_item", "requirement_item", "iter_rule_items", "as_dict", "as_list", "as_list_of_dicts", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sourceEvidence cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_registry_compiler.py", "sourceEvidence", "backend/app/drafting/application/evidence", "component", "backend.app.drafting.application.evidence.RuleRegistryCompilerComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sourceEvidence cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_registry_contract.py", "sourceEvidence", "backend/app/drafting/application/evidence", "dto", "backend.app.drafting.application.evidence.RuleRegistryContractDTO", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("contract_registry", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "sourceEvidence cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_registry_sections.py", "sourceEvidence", "backend/app/drafting/application/evidence", "component", "backend.app.drafting.application.evidence.RuleRegistrySectionsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("publisher_rule_registry", "topic_fabula_registry", "direct_context_registry", "ledger_registry", "brief_intent_registry", "registry_rule", "iter_rule_items", "as_dict", "as_list", "as_list_of_dicts", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "sourceEvidence cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_rule_registry_size.py", "sourceEvidence", "backend/app/drafting/application/evidence", "privateHelper", "backend.app.drafting.application.evidence.RuleRegistrySizePolicy", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("publication_size_registry", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "sourceEvidence cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_budget_resolver.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.DraftRunBudgetResolverComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("resolve_draft_run_budget", "budget_from_context", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_context_builder.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.DraftRunContextBuilderComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("build_draft_run_context_summary", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_context_payloads.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "dto", "backend.app.drafting.application.artifacts.DraftRunContextPayloadsDTO", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("context_from_payload", "context_to_payload", "context_input_summary", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "contextArtifacts cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_draft_step_service.py", "compatibilityShell", "backend/app/drafting/application/workflow", "service", "backend.app.drafting.application.workflow.DraftRunDraftStepService", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "compatibilityShell cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_payloads.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "dto", "backend.app.drafting.application.artifacts.DraftRunPayloadsDTO", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("request_to_payload", "request_from_payload", "draft_to_payload", "payload_section", "input_summary_from_request", ), "dto", "provider-free value/factory helper remains documented under the target DTO owner", "contextArtifacts cluster; dto target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_pipeline.py", "compatibilityShell", "backend/app/drafting/application/workflow", "service", "backend.app.drafting.application.workflow.DraftRunPipelineService", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "compatibilityShell cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_pipeline_ports.py", "compatibilityShell", "backend/app/drafting/application/workflow", "component", "backend.app.drafting.application.workflow.DraftRunPipelinePortsComponent", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_progress.py", "compatibilityShell", "backend/app/drafting/application/workflow", "component", "backend.app.drafting.application.workflow.DraftRunProgressComponent", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_service.py", "compatibilityShell", "backend/app/drafting/application/workflow", "service", "backend.app.drafting.application.workflow.DraftRunService", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "compatibilityShell cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_staleness.py", "compatibilityShell", "backend/app/drafting/application/workflow", "component", "backend.app.drafting.application.workflow.DraftRunStalenessComponent", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", ("inspect_draft_run_staleness", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_step_progress.py", "compatibilityShell", "backend/app/drafting/application/workflow", "component", "backend.app.drafting.application.workflow.DraftRunStepProgressComponent", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_run_step_progress_payload.py", "compatibilityShell", "backend/app/drafting/application/workflow", "component", "backend.app.drafting.application.workflow.DraftRunStepProgressPayloadComponent", "2.17.4.6.0.4", "legacy import remains until call sites move; no behavior may be added to the shim", ("step_artifact", "with_progress", "with_progress_payload", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "compatibilityShell cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_source_ledger_builder.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.SourceLedgerBuilderComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_source_ledger_sections.py", "contextArtifacts", "backend/app/drafting/application/artifacts", "component", "backend.app.drafting.application.artifacts.SourceLedgerSectionsComponent", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", ("brief_claims", "candidate_claims", "signal_claims", "topic_fabula_claims", "author_position_claims", "risks", "warnings", "base_forbidden_inferences", "topic_forbidden_inferences", "constraint_claim", "claim", "warning", "confidence_from_candidate", "confidence_from_author_evidence", "as_list", ), "component", "builder/parser/mapper helper becomes a method on the target component owner", "contextArtifacts cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_strategy_service.py", "planning", "backend/app/drafting/application/planning", "service", "backend.app.drafting.application.planning.DraftStrategyService", "2.17.4.6.0.4", "thin compatibility shim after Slice 2.17.4.6.0.4; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "planning cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_alternative_flow.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftValidationAlternativeFlowService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_evidence.py", "validation", "backend/app/drafting/application/validation", "privateHelper", "backend.app.drafting.application.validation.DraftValidationEvidenceHelpers", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("evidence_findings", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; privateHelper target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_linter.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftValidationLinterComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_operation_safety.py", "validation", "backend/app/drafting/application/validation", "policy", "backend.app.drafting.application.validation.DraftValidationOperationSafetyPolicy", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("safe_call", "failed_revision_result", "failed_pairwise_result", ), "policy", "behavioral decision helper becomes a method on the target policy owner", "validation cluster; policy target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_ranking_bridge.py", "validation", "backend/app/drafting/application/validation", "component", "backend.app.drafting.application.validation.DraftValidationRankingBridgeComponent", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "component", "builder/parser/mapper helper becomes a method on the target component owner", "validation cluster; component target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_report_flow.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftValidationReportFlowService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_step.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftValidationStepService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", ("validation_artifact", "validation_not_run_artifact", ), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validation_step_service.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftValidationStepService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
    _entry("backend/app/application/draft_validator_orchestrator.py", "validation", "backend/app/drafting/application/validation", "service", "backend.app.drafting.application.validation.DraftValidatorOrchestratorService", "2.17.4.6.0.5", "thin compatibility shim after Slice 2.17.4.6.0.5; behavior lives in the target bounded-context owner; no behavior may be added to the shim", (), "privateHelper", "legacy public helper becomes a private helper or method on the target owner during migration", "validation cluster; service target; generated from legacy surface triage for slice 2.17.4.6.0.4.0"),
)


def legacy_surface_inventory_payload() -> list[dict[str, object]]:
    return [entry.to_payload() for entry in LEGACY_DRAFT_RUN_SURFACE_INVENTORY]
